Add `<figure>` recipe
5t3ph/htmlrecipes pull request #3
Opened 2021-07-29 16:06 UTC by MWDelaney

Added `<figure>` recipe with a single image and caption. The `<figure>` section could be expanded to include other content examples, like code snippets, poems, etc. but this basic example is the best place to start.

2021-07-29 17:06 UTC, 5t3ph requested changes
Really excellent idea! Just a suggestion on improving the description, thanks!

2021-07-29 17:06 UTC, 5t3ph commented on src/snippets/figure.njk
> +  Usually a `<figure>` is an image, illustration, diagram, code snippet, etc. If your use case doesn't require a caption, the `<figcaption>` can be omitted.
Maybe link to MDN docs on this.

I would also like to work in a summarized note from (with link to) [this article](https://thoughtbot.com/blog/alt-vs-figcaption) talking about the relationship between using figcaption _and_ img `alt`

2021-07-29 17:32 UTC, MWDelaney commented
Here's an updated screenshot:

<img width="1066" alt="image" src="https://user-images.githubusercontent.com/2457670/127538106-d23ddeff-1db5-4c31-8113-b48b4bae9958.png">

2021-07-30 00:12 UTC, 5t3ph approved these changes
Great, publishing now, thanks!

2021-07-30 00:12 UTC, merged